general {
    lock_cmd = pidof hyprlock || hyprlock       # comando para bloquear
    before_sleep_cmd = loginctl lock-session    # bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # ligar monitor ao acordar
}

listener {
    timeout = 300                                # 5 minutos
    on-timeout = loginctl lock-session           # bloqueia a tela
}

listener {
    timeout = 600                                # 10 minutos
    on-timeout = hyprctl dispatch dpms off       # apaga o monitor
    on-resume = hyprctl dispatch dpms on         # liga ao voltar
}

listener {
    timeout = 900                                # 15 minutos
    on-timeout = systemctl suspend               # suspende o PC
}
