preload = /home/caiogouveia/Imagens/Wallpapers/02716_torcal_1920x1080.jpg
#set the default wallpaper(s) seen on initial load, depending on the number of monitors used
wallpaper = ,/home/caiogouveia/Imagens/Wallpapers/02716_torcal_1920x1080.jpg

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
