return {}
-- return {
--     "nvim-treesitter/nvim-treesitter",
--     build = ":TSUpdate",
--     event = { "BufReadPost", "BufNewFile" },
--     config = function()
--         local status_ok, treesitter = pcall(require, "nvim-treesitter.configs")
--         if not status_ok then
--             return
--         end
--         treesitter.setup({
--             ensure_installed = {
--                 "vimdoc", "javascript", "typescript", "tsx", "c", "lua", "rust",
--                 "jsdoc", "bash", "markdown", "markdown_inline"
--             },
--             sync_install = false,
--             auto_install = true,
--             indent = {
--                 enable = true
--             },
--             highlight = {
--                 enable = true,
--                 additional_vim_regex_highlighting = { "markdown" },
--             },
--         })
--     end
-- }
